---
# createUser.yml
# create a user
- name: create user
  hosts: my_hosts
  remote_user: lnxcfg 
  become: true
  become_method: sudo
  become_user: root

# Define variables
  vars:
    login:              'dbuser01'
    gecos:              'Database User01 Account'
    shell:              '/bin/bash'
    supplementalGroups: 'database'
    # created password prior with:
    # python -c 'import crypt,getpass; print crypt.crypt(getpass.getpass())'
    password:    '<REDACTED>'

   tasks:
        - name: create a user
          user:
            name: "{{ login }}"  #login id
            comment: "{{ gecos }}" #gecos field
            shell: "{{ shell }}"
            password: "{{ password }}"
            groups: "{{ supplementalGroups }}"
            append: yes 
            update_password: always

        - name: Add sudoers file
          file:
            owner: root
            group: root
            mode: 0400
            path: "/etc/sudoers.d/{{ login }}"
            state: touch

        - name: Add suders data
          blockinfile:
            path: "/etc/sudoers.d/{{ login }}" 
            block: |
              User_Alias {{ login|upper }} = %{{ login }}
              {{ login|upper }} ALL=(ALL)      ALL
