---
# Kubernetes initialization steps for Master.  Assumes that the generic installation has already been completed.    
- name: Initialize Kubernetes on a Master node 
  hosts: k8s-master
  remote_user: lnxcfg
  become: true
  become_method: sudo
  become_user: root

  tasks:  

     - name: Download the RBAC config file 
       get_url:
         url: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
         dest: /home/lnxcfg/rbac-kdd.yaml
         mode: 0440
       become: yes
       become_user: root

     - name: Download the Calico config file 
       get_url:
         url: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
         dest: /home/lnxcfg/calico.yaml
         mode: 0440
       become: yes
       become_user: root
  
     - name: Put cidr for overlay network into environment variable
       shell: MY_CALICO_CIDR=$( cat /home/lnxcfg/calico.yaml | grep -A 1 CALICO_IPV4POOL_CIDR | grep value | cut -d ':' -f2 | tr -d ' "')
       become: yes
       become_user: root

     #Start test of new variable approach
     - name: Define cidr for calico as a variable in the task
       shell: echo $( cat /home/lnxcfg/calico.yaml | grep -A 1 CALICO_IPV4POOL_CIDR | grep value | cut -d ':' -f2 | tr -d ' "')
       register: with_output
       become: yes
       become_user: root

     - name: Run kubeadm init using the calico variable just created
       shell: kubeadm init --kubernetes-version 1.13.1 --pod-network-cidr {{ item }} | tee kubeadm-init.out
       with_items: 
         - "{{ with_output.stdout_lines }}"
       become: yes
       become_user: root  
     #End test of new variable approach

     - name: Wait until the file /etc/kubernetes/admin.conf is present before continuing
       wait_for:
         path: /etc/kubernetes/admin.conf
       sudo: true
       sudo_user: lnxcfg

     - name: Create kube directory 
       command: mkdir -p $HOME/.kube
       sudo: true
       sudo_user: lnxcfg

     - name: copy admin_conf file into kube_config directory 
       command: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
       become: yes
       become_user: root  

     - name: Change ownership of kube_config directory 
       command: chown $(id -u):$(id -g) $HOME/.kube/config 
       sudo: true
       sudo_user: lnxcfg       
       
     # Do we really need to reboot before doing the remaining steps below 
     #- name: Reboot machine
     #  reboot:  
       
     - name: Apply the RBAC config file to the cluster
       shell: kubectl apply -f /home/lnxcfg/rbac-kdd.yaml
       become: yes
       become_user: root

     # Then deploy a pod network to the cluster 
     - name: Deploy a pod network to the cluster 
       command: kubectl apply -f calico.yaml
       sudo: true
       sudo_user: lnxcfg
