---
# Kubernetes installation steps that apply to all types of nodes.  Will be followed by specific additional steps for each type of node.  
- name: Install k8s generic all types of nodes.
  hosts: k8s-master, k8s-worker
  remote_user: lnxcfg
  become: true
  become_method: sudo
  become_user: root

  tasks:  

     - name: Perform yum update of all packages
       yum:
         name: '*'
         state: latest

     - name: Reboot machine
       reboot:
          
     - name: Remove any previous versions of docker
       command: yum -y remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine

     - name: Install package that will be needed later to disable SELinux
       command: yum -y install libselinux-python
       
     - name: Install docker 
       command: amazon-linux-extras install -y docker
       
     - name: Start docker
       command: systemctl start docker.service
       
     - name: Enable docker 
       command: systemctl enable docker.service
       
     - name: Add user to docker group
       command: usermod -a -G docker lnxcfg
      
     # Disable SELinux
     - name: Disable SELinux
       selinux:
         state: disabled
       become: yes
       become_user: root
       
     - name: Define k8s repo with serious security hole to be removed later
       shell:
         cmd: |
           cat <<EOF > /etc/yum.repos.d/kubernetes.repo
           [kubernetes]
           name=Kubernetes
           baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
           enabled=1
           gpgcheck=0
           repo_gpgcheck=0
           gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
           EOF
       become: yes
       become_user: root

     - name: Install kubelet kubeadm and kubectl
       command: yum -y install kubelet kubeadm kubectl

     - name: Enable kubelet before kubeadm  
       command: systemctl enable kubelet
       become: yes 
       become_method: sudo
       become_user: root
       