---
# testDist.yml
# create /etc/system-release using conditional statement
- name: test distribution and version
  hosts: my_hosts
  remote_user: lnxcfg
  become: true
  become_method: sudo
  become_user: root

  tasks:
        - name: create file based on distribution 
          copy:
             content: "{{ ansible_distribution }} version: {{ ansible_distribution_version }}"
             dest: /etc/system-release
          when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
